### ISSUE TITLE
zlib-bindings is marked deprecated on hackage

### ISSUE THREAD

**Issue by cartazio** [snapframework/io-streams#32]
https://hackage.haskell.org/package/zlib-bindings

might be worth figuring out something for the future maintainership thereof

**Comment by Piezoid** [comment]
Since version 0.6.0.0, zlib present a streaming API in Codec.Compression.Zlib.Internal. I don't know if the API is stable enough to be used in io-streams right now, maybe we should ask Duncan about it.

**Comment by gregorycollins** [comment]
Without proper control over flush, that streaming interface in `zlib` is useless to us.

I did take over maintainership of `zlib-bindings` from Michael and undeprecated it, but apparently once you mark a package as deprecated, uploading a new version doesn't clear the bit.

**Comment by hvr** [comment]
you have to clear the deprecation flag in the package maintainance settings in tge web ui
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gregorycollins** [comment]
It looks fixed on hackage now, and I have updated the maintainer info
