### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by rgrinberg** [snapframework/io-streams#34]
Is it possible to add io-streams to stackage? Even if you don't use stackage it should be helpful in managing upper bounds.

**Comment by nomeata** [comment]
I was about to report the same thing. Having this on stackage would make life easier for Distribution packagers as well.

See http://www.stackage.org/authors for instructions.

**Comment by gregorycollins** [comment]
I don't use stackage so this is not very high on my priority list, although I'm sure I'll get to it eventually.

**Comment by afcowie** [comment]
As far as I can tell, it is just adding the package to a control file.
You're already pretty tight with upper bounds so your packages (io-streams,
openssl-streams) should be easy to add. Then I can add http-streams.

**Comment by afcowie** [comment]
ping. You did it already; I was able to add **http-streams** on top as a result. You can close this now :)

**Comment by rgrinberg** [comment]
Thanks.
