### ISSUE TITLE
Accumulation of consumed bytes for an OutputStream not working

### ISSUE THREAD

**Issue by kosmoskatten** [snapframework/io-streams#38]
Hi,

From the API documentation I expect that the counting of consumed bytes would accumulate for an OutputStream.

`> (os, flush) <- Streams.listOutputStream :: IO (OutputStream BS.ByteString, IO [BS.ByteString])`
`> (os', counter) <- Streams.countOutput os`
`> counter`
`> 0`

If I now write the string "abc" to the stream it accounts the bytes as expected:

`> Streams.write (Just "abc") os'`
`> counter`
`> 3`

But if I write another string, e.g. "de", to the stream it only accounts for "de", not all data I have been written to the stream.

`> Streams.write (Just "de") os'`
`> counter`
`> 2`

I would have expected an answer of 5. The accounting of InputStreams work as I expect though.

Using version 1.2.1.2 if io-streams.

Cheers,
  --patrik

**Comment by gregorycollins** [comment]
Reading the count is destructive, i.e. it resets the value to its initial state of zero. This is true of `inputFoldM` and `outputFoldM` (which `countOutput` uses) as well.

**Comment by kosmoskatten** [comment]
Ahh, ok.

Cheers,
  --patrik
