### ISSUE TITLE
Add support for `primitive-0.6`

### ISSUE THREAD

**Issue by hvr** [snapframework/io-streams#39]
The main change in `primitive-0.6` according to the changelog is

> * Split PrimMonad into two classes to allow automatic lifting of primitive operations into monad transformers. The `internal` operation has moved to the `PrimBase` class.

Installing via `cabal install io-streams --allow-newer=primitive` actually works, so the API is at least superficially compatible.

See also http://hdiff.luite.com/cgit/primitive/commit?id=0.6 for what changed at the implementation level

**Comment by cartazio** [comment]
agreed, this should be done

@mightybyte  @gregorycollins  how can we help kick this along?

**Comment by gregorycollins** [comment]
I have changes queued to go out with io-streams 1.3, I'll need to backport a stability release (not ready to release 1.3 yet)

**Comment by gregorycollins** [comment]
Released

**Comment by hvr** [comment]
thanks! :beers:
