### ISSUE TITLE
Folds that don't reset accum on flush

### ISSUE THREAD

**Issue by LukeHoersten** [snapframework/io-streams#48]
`Combinators.inputFoldM` and `output` counterpart [reset the accum](https://github.com/snapframework/io-streams/blob/master/src/System/IO/Streams/Combinators.hs#L143) on flush. I have variants that don't do that but I think we need to talk about how to minimally represent this in the API without just copy/pasting the functions and removing the reset.

Ex:

``` haskell
fetch ref = atomicModifyIORef ref $ \x -> (initial, x)
```

@gregorycollins any thoughts about how this could be made more generic?

**Comment by gregorycollins** [comment]
A separate free function with copy-paste is totally fine here (these functions are short), the question is what the name should be. I don't have any wonderful ideas.

**Comment by LukeHoersten** [comment]
Same. How did you decide the default would be to clear the accum on flush? The clue could be there.

**Comment by gregorycollins** [comment]
Picking this up two years later: I don't remember exactly why I decided to clear the accumulator on flush, but I suspect it was to avoid retaining the value so it could be GC'd.

If you want to add these I'll merge a PR naming them with a `NoFlush` suffix. Closing this for now.

**Comment by LukeHoersten** [comment]
Sounds good. Let me check the state of my code. Thanks Greg.
