### ISSUE TITLE
Implicit buffering makes System.IO.Streams.Process impractical

### ISSUE THREAD

**Issue by polux** [snapframework/io-streams#52]
`runInteractiveCommand` and `runInteractiveProcess` in `System.IO.Streams.Process` both rely on  `handleToInputStream` which uses a buffer of size 32752. This makes it impossible to interact with processes which wait for requests on stdin and whose responses are shorter than 32752 bytes. To some extent it also makes writing requests to the process' stdin impractical. But this can be worked around by sending `Just ""` to the output stream, which flushes it.

**Comment by gregorycollins** [comment]
Yes, sending `Just ""` to things that buffer forces flush, that is standard throughout the library. Unfortunately it is not documented here, we should fix that.

AFAIK the 32k constant here just stipulates the value being sent to `read()`, we shouldn't be blocking if the downstream process sends a `write()` shorter than this. Do you have a repro?

**Comment by polux** [comment]
> Yes, sending Just "" to things that buffer forces flush, that is standard throughout the library. Unfortunately it is not documented here, we should fix that.

Actually this is documented, that's how I found out.

> AFAIK the 32k constant here just stipulates the value being sent to read(), we shouldn't be blocking if the downstream process sends a write() shorter than this. Do you have a repro?

Ok, my bad, it works indeed. I must have mixed up the two issues: I wasn't getting a response from my "service" because I wasn't flushing my requests I guess. Then I fixed both problems by changing the size of the buffer to one and concluded that this was needed for reading to.
