### ISSUE TITLE
Minor issue with lines-function (Streams.lines works differently than Prelude.lines)

### ISSUE THREAD

**Issue by gspia** [snapframework/io-streams#57]
Please, consider the following functions shown below and ghci-output (these are from the tutorial)

> *Main> pl "./sometext.txt" 
> ["a","b","c","d",""]
> *Main> pl2 "./sometext.txt" 
> ["a\nb\nc\nd\n"]
> *Main> wc2 "./sometext.txt" 
> 5
> *Main> wc Lines "./sometext.txt" 
> 5
> *Main> lines "a\nb\nc\nd\n"
> ["a","b","c","d"]
> *Main> BC.lines (BC.pack "a\nb\nc\nd\n")
> ["a","b","c","d"]

The 2nd last is from prelude and the last one from ByteString-package. It seems that Streams.lines will add an extra new-line to its output, which, in turn, causes the wc-example to show up a wrong answer. Comparing the implementations, this is somehow related to how Streams.splitOn works. 

Command line gives 4 lines (the file contains 4 chars each in separate lines):

> --: wc sometext.txt 
> 4 4 8 sometext.txt

Thus, the question is what should be done to make the wc-example behave like to cmd-line tool? (I tried to get rid of the last item by using what is available at the io-streams-lib but didn't succeed.)

```
import Data.Int
import Control.Monad 
import qualified Data.ByteString.Char8 as BC
import qualified System.IO.Streams as Stream
import           System.IO                                
import           System.Environment                      

pl :: FilePath -> IO ()
pl file = withFile file ReadMode $
  Stream.handleToInputStream >=> Stream.lines >=> Stream.toList >=> print

pl2 :: FilePath -> IO ()
pl2 file = withFile file ReadMode $
  Stream.handleToInputStream >=> Stream.toList >=> print

wc2 :: FilePath -> IO ()
wc2 file = withFile file ReadMode $
      Stream.handleToInputStream >=> Stream.lines >=> Stream.fold (\n _ -> n + 1) 0 >=> print

data Option = Bytes | Words | Lines

len :: Stream.InputStream a -> IO Int64
len = Stream.fold (\n _ -> n + 1) 0

wc :: Option -> FilePath -> IO ()
wc opt file = withFile file ReadMode $
  Stream.handleToInputStream >=> count >=> print
  where
    count = case opt of
      Bytes -> \is -> do
        (is', cnt) <- Stream.countInput is
        Stream.skipToEof is'
        cnt
      Words -> Stream.words >=> len
      Lines -> Stream.lines >=> len
```

**Comment by winterland1989** [comment]
I'd like to get consistent behavior with `Prelude` too, but the code of `splitAt` explicitly break this consistency with:

```
...
                         if S.null b'
                           then do
                             writeIORef ref ("" :)
                             return $ Just $! S.concat $ dl [a]
...
```

Is there any reason to do so? if not i'd like to send a  patch.

**Comment by gspia** [comment]
If you have a patch, I would be willing to try it (I would like to use the lines-functions and to not take corrective actions elsewhere, e.g. it is quite disturbing that otherwise nice wc-example is not working correctly). 
However, I don't know if there are other places or usages of `IO.Streams.ByteString.splitOn` that would break by changing the behaviour.
