### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [snapframework/io-streams#80]
See https://hackage.haskell.org/package/transformers-0.6.0.2/changelog.

Could you upload a compatible release or revisions? Thanks! :)

**Comment by sjakobi** [comment]
With `--allow-newer` the build already succeeds, so it might be as simple as bumping some bounds.

**Comment by sjakobi** [comment]
Ping! :)

**Comment by ysangkok** [comment]
@mightybyte This has waited quite a while. Do you have time to review it?

**Comment by andreasabel** [comment]
PR at:
- #84

**Comment by andreasabel** [comment]
@sjakobi : This issue is fixed by 1.5.2.1 revision and 1.5.2.2. release.  Can be closed, I suppose.

**Comment by sjakobi** [comment]
That's great to hear! Thank you! :)
